[tool.poetry]
name = "advent-2023"
version = "0.1.0"
description = ""
authors = ["Zach Hindes <zach@dowhatnow.net>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
